### ISSUE TITLE
failed to execute goal com.soebes.maven.plugins:iterator-maven-plugin:0.2

### ISSUE THREAD

**Issue by Lixin228** [khmarbaise/iterator-maven-plugin#20]
Hello,when i run mvn validate -DrvMonitorBase=<RV-Monitor_HOME>,i meet a error:failed to execute goal com.soebes.maven.plugins:iterator-maven-plugin:0.2executor<default> on project javamop:command execution failed.can not run program "mvn" <in directory "E:\jAVAMOP\javamop-4.2">:CreateProcess error=2,系统找不到指定文件。

**Comment by khmarbaise** [comment]
Can you give me a full example project...which reproduces the problem?

**Comment by khmarbaise** [comment]
Can you also check with release 0.3 ?

**Comment by khmarbaise** [comment]
Unfortunately no feedback so i close the issue.
