### ISSUE TITLE
iterator-maven-plugin don't include the license file

### ISSUE THREAD

**Issue by puntogil** [khmarbaise/iterator-maven-plugin#21]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by puntogil** [comment]
All java source files are without license headers. Please, confirm the licensing of code and/or content/s
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

**Comment by khmarbaise** [comment]
What i don't understand why it will be packaged, cause the plugin should be consumed via maven central repository.

**Comment by puntogil** [comment]
Fedora [1] do not accept to use pre built libraries or binaries [2]
Usually we import and use latest release of any software
Our build system do not provides also a web connection, for access to a remote repository
see

https://kojipkgs.fedoraproject.org//work/tasks/5269/11375269/build.log
list of the libraries used for build
https://kojipkgs.fedoraproject.org//work/tasks/5269/11375269/root.log

[1] https://en.wikipedia.org/wiki/Fedora_%28operating_system%29
[2] https://fedoraproject.org/wiki/Packaging:Java#Pre-built_dependencies
     https://fedoraproject.org/wiki/Packaging:Guidelines#No_inclusion_of_pre-built_binaries_or_libraries
