### ISSUE TITLE
iterator plugin gets confused and merges multiple executions together

### ISSUE THREAD

**Issue by beirtipol** [khmarbaise/iterator-maven-plugin#24]
I have a configuration which invokes maven-resources-plugin:copy-resources and maven-dependency-plugin:copy-dependencies on 2 different plugins. I get error messages saying that parameters from the copy-resources execution are being passed to the copy-dependencies. 

Is it supported to use iterator for executions of different plugins?

**Comment by khmarbaise** [comment]
Can you show the pom file ?

**Comment by beirtipol** [comment]
Hi Karl,

Am away for a week but will dig it up when I get back.

**Comment by beirtipol** [comment]
Hi Karl,

Back today and trying to get it working again. Currently I'm just trying to get a single plugin working but it's failing to do anything.

    <plugin>
    	<groupId>com.soebes.maven.plugins</groupId>
    	<artifactId>iterator-maven-plugin</artifactId>
    	<version>0.3</version>
    	<executions>
    		<execution>
    			<phase>validate</phase>
    			<goals>
    				<goal>iterator</goal>
    			</goals>
    			<configuration>
    				<pluginExecutors>
    					<pluginExecutor>
    						<plugin>
    							<groupId>org.apache.maven.plugins</groupId>
    							<artifactId>maven-dependency-plugin</artifactId>
    						</plugin>
    						<goal>copy-dependencies</goal>
    						<configuration>
    							<includeArtifactIds>myproject-environment</includeArtifactIds>
    							<includeClassifiers>@item@</includeClassifiers>
    							<outputDirectory>${getdown.builddirectory}/@item@</outputDirectory>
    							<stripVersion>true</stripVersion>
    							<excludeTypes>zip,war</excludeTypes>
    						</configuration>
    					</pluginExecutor>
    				</pluginExecutors>
    				<items>
    					<item>environment1</item>
    					<item>environment2</item>
    				</items>
    			</configuration>
    		</execution>
    	</executions>
    </plugin>

This configuration works if the maven-dependency-plugin is executed by itself. If I turn on debug mode I can see the that the maven-dependency-plugin is being 'configured' but not executed:

    9985 [INFO] ------ (environment1) org.apache.maven.plugins:maven-dependency-plugin:2.10:copy-dependencies
    9985 [DEBUG] Configuring mojo org.apache.maven.plugins:maven-dependency-plugin:2.10:copy-dependencies from plugin realm ClassRealm[    plugin>org.apache.maven.plugins:maven-dependency-plugin:2.10-18629080, parent: sun.misc.Launcher$AppClassLoader@546b97fd]
    9987 [DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-dependency-plugin:2.10:copy-dependencies' with basic configurator -->
    9987 [DEBUG]   (f) includeArtifactIds = calypso-env
    9987 [DEBUG]   (f) includeClassifiers = environment1
    9988 [DEBUG]   (s) outputDirectory = C:\dev\source\myassembling-project\target\environment1
    9989 [DEBUG]   (s) stripVersion = true
    9989 [DEBUG]   (f) addParentPoms = false
    9989 [DEBUG]   (s) copyPom = false
    9990 [DEBUG]   (f) excludeTransitive = false
    9990 [DEBUG]   (s) failOnMissingClassifierArtifact = false
    9991 [DEBUG]   (s) local =       id: local
          url: file:///c:/dev/maven/repo/
       layout: default
    snapshots: [enabled => true, update => always]
     releases: [enabled => true, update => always]
    
    9992 [DEBUG]   (s) markersDirectory = C:\dev\source\myassembling-project\target\dependency-maven-plugin-markers
    9992 [DEBUG]   (f) outputAbsoluteArtifactFilename = false
    9993 [DEBUG]   (f) overWriteIfNewer = true
    9993 [DEBUG]   (f) overWriteReleases = false
    9994 [DEBUG]   (f) overWriteSnapshots = false
    9994 [DEBUG]   (s) prependGroupId = false
    9994 [DEBUG]   (f) project = MavenProject: com.mygroup:myassembling-project:2016.03.05.1-SNAPSHOT @ C:\dev\source\myassembling-    project\pom.xml
    9995 [DEBUG]   (f) reactorProjects = [MavenProject: com.mygroup:myassembling-project:2016.03.05.1-SNAPSHOT @     C:\dev\source\myassembling-project\pom.xml]
    9996 [DEBUG]   (s) remoteRepos = [      id: calypso-release
          url: http://calypsoarchiva/repository/calypso-release/
       layout: default
    snapshots: [enabled => false, update => never]
     releases: [enabled => true, update => always]
    ,       id: calypso-snapshot
          url: http://calypsoarchiva/repository/calypso-snapshot/
       layout: default
    snapshots: [enabled => true, update => always]
     releases: [enabled => false, update => always]
    ,       id: calypso-archiva
          url: http://calypsoarchiva/repository/internal
       layout: default
    snapshots: [enabled => false, update => daily]
     releases: [enabled => true, update => daily]
    ]
    9997 [DEBUG]   (f) silent = false
    9998 [DEBUG]   (s) skip = false
    9998 [DEBUG]   (f) stripClassifier = false
    9999 [DEBUG]   (f) useBaseVersion = true
    9999 [DEBUG]   (s) useRepositoryLayout = false
    10000 [DEBUG]   (s) useSubDirectoryPerArtifact = false
    10001 [DEBUG]   (s) useSubDirectoryPerScope = false
    10001 [DEBUG]   (s) useSubDirectoryPerType = false
    10001 [DEBUG] -- end configuration --

Any idea what I might be doing wrong?

**Comment by khmarbaise** [comment]
Can you please make a test project which shows the wrong behaviour...

**Comment by beirtipol** [comment]
Hi Karl,

Apologies on the delay getting back to you. I've not had any success making
a test project to display the error. I would suggest you close the issue
and I'll raise again with a reproducible snippet if I find it.

**Comment by khmarbaise** [comment]
No apologies needed. It's very appreciated that you give feedback. Many thanks. So i close it. If you have  a reproducible part please open an issue. Thanks.
