### ISSUE TITLE
Add possibility to set properties for each item

### ISSUE THREAD

**Issue by garagatyi** [khmarbaise/iterator-maven-plugin#26]
I'm using iterator plugin in Eclipse Che project https://github.com/eclipse/che-lib/blob/master/websocket-terminal/pom.xml

I need to build golang application for different architectures. It requires environment variable. I use maven exec plugin and would want to make pom more pretty with iterator plugin. But it is not possible to set these variables because I can't set properties for each item.
It would be really useful if iterator plugin supports such configuration:
```xml
<items>
    <item>
        <value>linux_amd64</value>
        <properties>
            <goos>linux</goos>
            <goarch>amd64</goarch>
        </properties>
    </item>
    <item>
        <value>linux_arm7</value>
        <properties>
            <goos>linux</goos>
            <goarch>arm</goarch>
            <goarm>7</goarm>
        </properties>
    </item>
</items>
```

**Comment by khmarbaise** [comment]
Can you take a look with the current state and check if it works for you?

**Comment by garagatyi** [comment]
It works like a charm! Thank you a lot! I've just submitted a PR with usage of new syntax /eclipse/che-lib/pull/7

**Comment by khmarbaise** [comment]
I think it's time to make it available via Maven Central...WDYT ?

**Comment by khmarbaise** [comment]
Release to Central done. Take some time to synchronize...

**Comment by garagatyi** [comment]
Awesome! Thank you!
