### ISSUE TITLE
Iterator should not  fail with no item

### ISSUE THREAD

**Issue by damiendsl** [khmarbaise/iterator-maven-plugin#35]
I have tried example using `<content>`  echoing eins, zwei, drei
if content  is empty , it fails  in 

> [ERROR] Failed to execute goal com.soebes.maven.plugins:iterator-maven-plugin:0.4:iterator (default) on project content-testempty: You can use only one element. Either items, itemsWithProperties, content or folder element but not more than one of them. -> [Help 1]

Logically , I would have expected that  this does nothing in such a case , eventually logging that there is nothing to do but not failing(  or if you prefer to see it failing  then it should not give this error message but something like ' no item found.. ') . 

[pom.xml.zip](https://github.com/khmarbaise/iterator-maven-plugin/files/400298/pom.xml.zip)

**Comment by khmarbaise** [comment]
Absolute right...I will take a look...thanks for your support...
