### ISSUE TITLE
How to pass system properties from command line to invoker

### ISSUE THREAD

**Issue by nuvitong** [khmarbaise/iterator-maven-plugin#44]
Hi,

I'm trying to pass system properties from command line with `-D` to the iterator:invoker. Unfortunately those values are not present during the iteration.

    > mvn package -Pinvoker -Dzzz="hello world" -Denvironment=local
    [INFO] Scanning for projects...
    [INFO]
    [INFO] ------------------------------------------------------------------------
    [INFO] Building invoker-with-system-properties 1.0-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO]
    [INFO] --- maven-antrun-plugin:1.8:run (echo-properties) @ test-invoker-with-system-properties ---
    [INFO] Executing tasks

    main:
         [echo] environment: local
         [echo] profile-name: ${profile-name}
         [echo] zzz: hello world
    [INFO] Executed tasks
    [INFO]
    [INFO] --- iterator-maven-plugin:0.5.0:invoker (invoke-with-system-properties) @ test-invoker-with-system-properties ---
    [INFO] ------  iterator-maven-plugin ( iteration: foo )
    [INFO] [INFO] Scanning for projects...
    [INFO] [INFO]
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] Building invoker-with-system-properties 1.0-SNAPSHOT
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO]
    [INFO] [INFO] --- maven-antrun-plugin:1.8:run (echo-properties) @ test-invoker-with-system-properties ---
    [INFO] [INFO] Executing tasks
    [INFO]
    [INFO] main:
    [INFO]      [echo] environment: ${environment}
    [INFO]      [echo] profile-name: foo
    [INFO]      [echo] zzz: bye, bye
    [INFO] [INFO] Executed tasks
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] BUILD SUCCESS
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] Total time: 0.518 s
    [INFO] [INFO] Finished at: 2017-07-28T16:03:08+02:00
    [INFO] [INFO] Final Memory: 5M/15M
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] ------ Maven call was Ok.
    [INFO] ------  iterator-maven-plugin ( iteration: bar )
    [INFO] [INFO] Scanning for projects...
    [INFO] [INFO]
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] Building invoker-with-system-properties 1.0-SNAPSHOT
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO]
    [INFO] [INFO] --- maven-antrun-plugin:1.8:run (echo-properties) @ test-invoker-with-system-properties ---
    [INFO] [INFO] Executing tasks
    [INFO]
    [INFO] main:
    [INFO]      [echo] environment: ${environment}
    [INFO]      [echo] profile-name: bar
    [INFO]      [echo] zzz: bye, bye
    [INFO] [INFO] Executed tasks
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] BUILD SUCCESS
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] Total time: 0.521 s
    [INFO] [INFO] Finished at: 2017-07-28T16:03:10+02:00
    [INFO] [INFO] Final Memory: 5M/15M
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] ------ Maven call was Ok.
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 4.032 s
    [INFO] Finished at: 2017-07-28T16:03:10+02:00
    [INFO] Final Memory: 6M/15M
    [INFO] ------------------------------------------------------------------------

I would expect, that the property `${environment}` is always printed with the passed value _local_, as well as the property `${zzz}` printed with the passed value _hello world_.

Do I miss something?

Please find attached the according pom.
[pom.xml.txt](https://github.com/khmarbaise/iterator-maven-plugin/files/1183266/pom.xml.txt)

**Comment by dmn1k** [comment]
Fixed by #45 

"environment" still has to be declared inside the pom to be able to override it by a system property though.
It is not possible to simply pass all System properties to the new process since that would override necessary configuration options with wrong values.

**Comment by nuvitong** [comment]
Setting properties via the plugin's "properties"-section doesn't work, as those won't be passed to the `InvocationRequeset`'s properties. Only the properties of `ItemWithProperties` can be used. Unfortunately I'd like to iterate over a dynamic list of items (that's why I used `<content />` in the example), so `ItemWithProperties` doesn't work for me either.

@khmarbaise it would be nice, if you could check the PR and merge it, if it meets your requirements. I would be even happier, if you could release a new version with this fix.
