### ISSUE TITLE
Component descriptor cannot be found in the component repository

### ISSUE THREAD

**Issue by kexiuru** [khmarbaise/iterator-maven-plugin#48]
using version: 0.5.1
exception:

the requirement ComponentRequirement{role='org.codehaus.plexus.logging.Logger', roleHint='', fieldName='logger'} was missing

**Comment by kexiuru** [comment]
import: Entry[import org.apache.maven from realm null]

realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/commons-cli-1.2.jar
urls[1] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/commons-logging-api-1.1.jar
urls[2] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/google-collections-1.0.jar
urls[3] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/jetty-client-7.0.0.v20091005.jar
urls[4] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/jetty-http-7.0.0.v20091005.jar
urls[5] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/jetty-io-7.0.0.v20091005.jar
urls[6] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/jetty-util-7.0.0.v20091005.jar
urls[7] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/log4j-1.2.12.jar
urls[8] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/maven-artifact-3.0-SNAPSHOT.jar
urls[9] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/maven-compat-3.0-SNAPSHOT.jar
urls[10] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/maven-core-3.0-SNAPSHOT.jar
urls[11] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/maven-embedder-3.0-SNAPSHOT.jar
urls[12] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/maven-model-3.0-SNAPSHOT.jar
urls[13] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/maven-model-builder-3.0-SNAPSHOT.jar
urls[14] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/maven-plugin-api-3.0-SNAPSHOT.jar
urls[15] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/maven-settings-3.0-SNAPSHOT.jar
urls[16] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/plexus-build-api-0.0.6.jar
urls[17] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/plexus-cipher-1.4.jar
urls[18] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/plexus-component-annotations-1.5.4.jar
urls[19] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/plexus-container-default-1.5.4.jar
urls[20] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/plexus-interpolation-1.11.jar
urls[21] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/plexus-sec-dispatcher-1.3.jar
urls[22] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/plexus-utils-2.0.1.jar
urls[23] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/wagon-file-1.0-beta-6.jar
urls[24] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/wagon-http-jetty-client-1.0-SNAPSHOT.jar
urls[25] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/wagon-provider-api-1.0-beta-6.jar
urls[26] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/xbean-reflect-3.4.jar
Number of foreign imports: 0

-----------------------------------------------------: Error constructing component role: 'org.apache.maven.reporting.exec.MavenPluginManagerHelper', implementation: 'org.apache.maven.reporting.exec.DefaultMavenPluginManagerHelper', role hint: 'default': Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.codehaus.plexus.logging.Logger for injection private org.codehaus.plexus.logging.Logger org.apache.maven.reporting.exec.DefaultMavenPluginManagerHelper.logger: Composition failed of field logger in object of type org.apache.maven.reporting.exec.DefaultMavenPluginManagerHelper because the requirement ComponentRequirement{role='org.codehaus.plexus.logging.Logger', roleHint='', fieldName='logger'} was missing): Component descriptor cannot be found in the component repository
      role: org.codehaus.plexus.logging.Logger
  roleHint: 
classRealm: none specified
-> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by khmarbaise** [comment]
Hi,
I'm not sure how things like this appear:
```
urls[12] = file:/C:/SWDTOOLS/IBM/RAD95/plugins/org.maven.ide.eclipse.maven_embedder_0.10.2.20100623-1649/jars/maven-model-3.0-SNAPSHOT.jar
```
cause the maven-module-3.0-SNAPSHOT is not expected to be used. 

The question is: Which version of Maven do you use? Does your project run on plain command line? 

Which M2E Integration do you use in Eclipse? And which Eclipse version do you use?

**Comment by kexiuru** [comment]
Hi Khmarbaise,
Thanks for your reply. 
I am using RAD 9.5 for develop tool. Details as below:
    _IBM Rational® Application Developer for WebSphere® Software
    Version: 9.5
    Build ID: RADO95-I20150908_2025_
M2E Integration seems using   0.10.2.20100623-1649.

**Comment by kexiuru** [comment]
Error constructing component role: 'org.apache.maven.reporting.exec.MavenPluginManagerHelper', implementation: 'org.apache.maven.reporting.exec.DefaultMavenPluginManagerHelper', role hint: 'default': Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.codehaus.plexus.logging.Logger for injection private org.codehaus.plexus.logging.Logger org.apache.maven.reporting.exec.DefaultMavenPluginManagerHelper.logger: Composition failed of field logger in object of type org.apache.maven.reporting.exec.DefaultMavenPluginManagerHelper because the requirement ComponentRequirement{role='org.codehaus.plexus.logging.Logger', roleHint='', fieldName='logger'} was missing): Component descriptor cannot be found in the component repository

**Comment by kexiuru** [comment]
Have fixed. Seems caused by JDK version.  Thanks.
